# Generated by Django 5.0.1 on 2024-01-03 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from exercise_app.models import Country, CustomUser
import random

def populate_random_user(apps, schema_editor):
    countries = Country.objects.all()
    users = CustomUser.objects.all()
    
    for country in countries:
        random_user = random.choice(users)
        country.my_user = random_user
        country.save()
    



class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0002_country_my_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='my_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(populate_random_user)
    ]
